Issue/54 git workflow
epimorphics/ukhpi pull request #312
Opened 2021-12-01 15:33 UTC by mairead

2021-12-10 10:59 UTC, andrew-pickin-epi requested changes
The two main issues here are indiscriminate copy using rm in dockerfile, and the way environment variables are being used.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Dockerfile
I still don't see the point of these environment variables. 
They are still not documented.
All they seem to be is altering the behaviour of the application when running in a proxy environment or locally. This is in essence the difference between production and development (or maybe should be included in a `docker.rb` ?). I would have though that was the purpose of `RAILS_ENV`. There is no explanation of the difference between the two rails environments. Why not encapsulate these two behaviour patterns in the two config files?
There is no explanation of the two configurations?
I generally dislike the use of env var here. They are not being used to turn on/off particular switches that the deployment might vary but setting production behaviour.  This is akin to exposing methods that should be private.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Makefile
> +all: publish
I'm not sure the default target should be `publish`. It's probably a bit dangerous. `image` would probably be better.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on entrypoint.sh
>    export SECRET_KEY_BASE=`./bin/rails secret`
Should this file be managing the pid lock file?

2021-12-10 10:59 UTC, andrew-pickin-epi commented on deployment.yaml
> +  - tag: "v{ver}-rc"
`pre-prod` doesn't exist. 
`dev-infrastructure` should probably be folded in `dev` by now.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on entrypoint.sh
>    export SECRET_KEY_BASE=`./bin/rails secret`
I'd like to to see tests for expected mandatory env vars here. Specifically `API_SERVICE_URL` being set.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Dockerfile
> +ENV API_SERVICE_URL = 'http://localhost:8080'
Why is `API_SERVICE_URL` being set?
What happens if this connection is refused?
Better to:

- not set by default
- test for presence in entrypoint - and exit if not with suitable error
- handle the retry in application if connection refused with suitable error

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Makefile
> +TAG?=$(shell if git describe > /dev/null 2>&1 ; then   git describe; else   git rev-parse --short HEAD; fi)
Might be nice to capture VERSION from `version.rb` here. Something like:
```
COMMIT=$(?=$(shell if git describe > /dev/null 2>&1 ; then git describe; else git rev-parse --short HEAD; fi)
VERSION?=$(shell ruby -e 'require "./app/lib/version" ; puts Version::VERSION')
TAG?=${VERSION}-${COMMIT}
```

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Dockerfile
> +ENV API_SERVICE_URL = 'http://localhost:8080'
This is probably the only true env var for this container. 
It should be documented.  I'd like to see description of the expected behaviour of the container under the various error scenarios and how failure to connect to this service is notified.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on .gitignore
>  /yarn-error.log
leading slash?

2021-12-10 10:59 UTC, andrew-pickin-epi commented on .gitignore
> +.github-token
I like to keep these files alphabetical. It makes doing diffs easier in the long term. 
Keep comments out (put them in some coding practice doc) and just use `sort`.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Dockerfile
> +COPY . .
Copying everything? This is explicitly frowned upon in the current practice doc.
Either be selective/use a `.dockerignore`.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Dockerfile
> +  && rm -rf node_modules
This looks wrong. Using `rm` here will break the dockerfile copy cache resulting in longer build times. 
Copy only what you need.

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Makefile
> +.PHONY:	assets clean image modules publish realclean run tag test vars
add `lint`

2021-12-10 10:59 UTC, andrew-pickin-epi commented on Dockerfile
> +COPY --from=builder /usr/src/app     ./app
`COPY` with `--chown` on line 51 would make line 53 redundant.

2021-12-14 09:14 UTC, mairead commented on Dockerfile
> +COPY . .
we have got a .dockerignore. Is that enough?

2021-12-14 09:38 UTC, mairead commented on deployment.yaml
> +  - tag: "v{ver}-rc"
I am assuming we're going to be running QA on dev-infrastructure for at least a couple of months so I figured we're not going to roll in to dev till then?

2021-12-14 14:04 UTC, mairead commented on entrypoint.sh
>    export SECRET_KEY_BASE=`./bin/rails secret`
I'm not sure how to structure a test to check if the default URL I'm passing is valid. Are we just testing this variable isn't empty or are we testing that the API URL can connect to something?

2021-12-14 14:21 UTC, mairead commented on Makefile
> +TAG?=$(shell if git describe > /dev/null 2>&1 ; then   git describe; else   git rev-parse --short HEAD; fi)
I don't think that we have 'ruby' so we can't retrieve the version. I can run Make tag locally but this fails in CI and I'm assuming it's because it can't build the app version string

2021-12-15 09:16 UTC, mairead commented
git describe gives you the last created tag and commit hash. Having both current version number and the last released tag seems a bit redundant to me. I think it would be better to pick one or the other

2021-12-15 12:41 UTC, andrew-pickin-epi commented on Makefile
I think this is wrong.  
`TAG` should be `${VERSION}-${COMMIT}` it's just the wrong way round.

If you want to tag the docker image be the version defined in the code, rather than the git tag, you don't want the describe. So `COMMIT` becomes 
`COMMIT=$(shell git rev-parse --short HEAD)`

2021-12-15 12:47 UTC, andrew-pickin-epi commented on entrypoint.sh
>    export SECRET_KEY_BASE=`./bin/rails secret`
Just empty. At least in `entrypoint.sh`.  It's only meant to catch the miss-configured deployment.
The app itself needs to handle endpoint not being contactable, or indeed going away.

2021-12-21 14:29 UTC, joescottdave approved these changes
Lgtm

2021-12-21 14:54 UTC, merged