Update README with ssh tunnel instructions
epimorphics/ukhpi pull request #313
Opened 2021-12-08 17:18 UTC by ijdickinson

Access to the data API on the new infrastructure is different than it
was on the old system. After some help from @mika018 (thanks Mihajlo!) I
was able to get an ssh tunnel working correctly.

These instructions work on Linux (Ubuntu 21.04). They may need amending
and tweaking to cover MacOS and Windows.

2021-12-15 11:12 UTC, joescottdave commented on README.md
> +Assuming this succeeds, you can set up an ssh tunnel to map the port where the data
For the completely uninitiated who are following this might be worth throwing in a line about what "this works" would look like and then exiting the shell?

2021-12-15 12:07 UTC, joescottdave reviewed
I've followed along with this, I've made one suggestion where I can see an earlier version of me following along just fine and then proceeding to enter the remaining commands into the shell of the ssh'd machine.

2021-12-16 10:17 UTC, mika018 reviewed
Looks good :+1: 
I added a couple of suggestions.

2021-12-16 10:17 UTC, mika018 commented on README.md
> +```
Maybe add a line to remind users to close the connection after they are done using it by killing the background process using it's PID.
`kill 71358` in this example.

2021-12-16 10:17 UTC, mika018 commented on README.md
> +$ ssh hmlr_dev_pres_071
The server name (or id - 071 in this case) is variable and will not always be 071. I think it updates every time we upgrade the server but don't quote me on this, it's a question for @andrew-pickin-epi.
You can use sensu to find out which entities run in which environment, here's a link for dev: https://sensu-hmlr.epimorphics.net/c/~/n/dev/entities. I would suggest adding an extra step prior to this one for determining the right server name using the link above.

2022-01-04 16:22 UTC, ijdickinson commented on README.md
> +$ ssh hmlr_dev_pres_071
Good catch, thanks @mika018. I've added a section to address this

2022-01-04 16:22 UTC, ijdickinson commented on README.md
> +```
Good suggestion. I've added some content to that effect

2022-01-04 16:23 UTC, ijdickinson commented on README.md
> +Assuming this succeeds, you can set up an ssh tunnel to map the port where the data
Thanks. I've added the sample output, and a note about shutting down the ssh process at the end as well.

2022-01-05 11:35 UTC, mika018 approved these changes

2022-01-05 11:36 UTC, mika018 commented
All looks good now from my point of view :+1:

2022-01-10 10:24 UTC, andrew-pickin-epi commented on README.md
> +$ ssh hmlr_dev_pres_071
I'd prefer not to do it this way. 
Way not just access the API LB directly? Then you don't need to know the name of the host.

If this is currently blocked but security groups, it can be in dev, and maybe even via the VPN for other environments.

I would request that in future folk don't go off down ssh tunnel route but discuss their requirements so less ad hoc solutions can be implemented.

2022-01-10 10:28 UTC, andrew-pickin-epi requested changes

2022-01-10 10:28 UTC, andrew-pickin-epi commented on README.md
> +#### Setting up an ssh tunnel to access the data service
Please don't make this offical.

SSH access to LR should reference not duplicate the wiki

2022-01-10 10:28 UTC, andrew-pickin-epi commented on README.md
> +Assuming this succeeds, you can set up an ssh tunnel to map the port where the data
NO.

Please stop baking ssh tunnels to the way we work.
If their is a need to access a host then add a requirement and let work the problem properly.
Either use the VPN or let's fix the SGs

2022-01-12 17:17 UTC, ijdickinson commented
As has been discussed on Slack, we are planning to have a meeting to discuss better alternatives, and then document the preferred pattern. In the meantime, I am closing this PR.

Captured as epimorphics/hmlr-linked-data#75

2022-01-12 17:17 UTC, closed without merging