Issue/9 change duration unit return type to integer
epimorphics/ukhpi pull request #361
Opened 2023-01-26 14:58 UTC by jonrandahl

2023-01-27 12:00 UTC, jonrandahl commented on lib/tasks/location.rake
> +    squery = "#{ENV.fetch('FUSEKI', '/home/ian/dev/java/apache-jena-fuseki')}/bin/s-query"
@der could you shed any light on this use of fuseki as I've not had any interaction with it and would like to clean up this fallback path if at all possible?

2023-01-27 12:01 UTC, jonrandahl commented on lib/tasks/location.rake
> +    squery = "#{ENV.fetch('FUSEKI', '/home/ian/dev/java/jena-fuseki')}/bin/s-query"
Same on this one too (@der )

2023-01-27 15:00 UTC, der commented on lib/tasks/location.rake
> +    squery = "#{ENV.fetch('FUSEKI', '/home/ian/dev/java/apache-jena-fuseki')}/bin/s-query"
`s-query` is a command line tool for running a Sparql query against a remote sparql endpoint. Looks like the rake script is executing that as a process to query the data (from either production, as here, or a development service (see next one, though the address of the development service will vary depending on the circumstances).

The environment variable `FUSEKI` is being used to allow you set where your fuseki or jena install sits so it can find the script. Ian has baked in a fallback for him which is slightly naughty but understandable. Anyone else running will need to make sure to set the right path in that env variable.

Though normally that variable would be `FUSEKI_HOME`, which is what fuseki itself uses, so would be worth changing that.

This is a "when the boundaries change" task so rarely used and will generally need some care when running anyway because it'll depend where the draft boundary data has been loaded. So having to ensure you have a local Jena or fuseki install doesn't seem that problematic.

However, if you want to eliminate the dependency then `s-query` is just a [self contained script](https://github.com/apache/jena/blob/main/jena-fuseki2/apache-jena-fuseki/bin/s-query). So you could include a copy of that locally in the repo and point to that as the default. As it happens the script is written in ruby but I don't suggest exploiting that fact. Just include it as a file to be executed as in the current pattern or leave it alone and just print a warning if `FUSEKI_HOME` isn't set.

2023-03-13 12:18 UTC, jonrandahl commented on lib/tasks/location.rake
> +    squery = "#{ENV.fetch('FUSEKI', '/home/ian/dev/java/apache-jena-fuseki')}/bin/s-query"
This has been resolved by adding the `s-query` file to the `bin` directory and setting the fallback value to the root path as such:

```rake
root = Rails.root.to_s
squery = "#{ENV.fetch('FUSEKI_HOME', root)}/bin/s-query"
server = ENV.fetch('SERVER', 'https://landregistry.data.gov.uk/landregistry/query')
```

2023-03-13 12:19 UTC, jonrandahl commented on lib/tasks/location.rake
> +    squery = "#{ENV.fetch('FUSEKI', '/home/ian/dev/java/jena-fuseki')}/bin/s-query"
See above 👆

2023-03-21 17:48 UTC, andrew-pickin-epi requested changes
Please fix as per LR Landing, The I will review.

2023-03-21 19:12 UTC, der approved these changes
Ditto as for ppd, sr, and landing.

2023-04-12 09:25 UTC, andrew-pickin-epi requested changes

2023-04-12 09:25 UTC, andrew-pickin-epi commented on config.ru
> +else
Map is required in `development` mode too to allow for running locally behind proxy.

2023-04-12 09:25 UTC, andrew-pickin-epi commented on config/environments/development.rb
> -  config.relative_url_root = ENV.fetch('RAILS_RELATIVE_URL_ROOT', '/')
You seen to be removing the change that allows for running as rails application locally with a proxy.

2023-05-09 15:45 UTC, andrew-pickin-epi approved these changes

2023-05-09 15:51 UTC, merged